logo_text: ToD

menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  Book: book
  About: about
  RSS: /atom.xml

excerpt_link: Read More
toc: false
fancybox: true

root: https://mycaule.github.io/
google_analytics: UA-108556432-1
facebook_social: 1968068840134141

favicon: /favicon.png
